/**
 * PCRWR NWQL potable-water parameter catalog (PSQCA / NSDWQ 2010).
 * Mirrors the chemical & microbiology test report layout.
 */

export type LimitOperator =
  | 'NONE'
  | 'MAX_INCLUSIVE'
  | 'MAX_EXCLUSIVE'
  | 'RANGE'
  | 'EQUALS_ZERO'
  | 'QUALITATIVE';

export type ParameterCategory =
  'PHYSICAL_AESTHETIC' | 'CHEMICAL' | 'TRACE_ELEMENT' | 'MICROBIOLOGICAL';

export type ParameterConformityGroup =
  'PHYSICAL' | 'CHEMICAL' | 'TRACE' | 'MICROBIAL';

export type WaterQualityParameterDef = {
  code: string;
  name: string;
  category: ParameterCategory;
  conformityGroup: ParameterConformityGroup;
  sortOrder: number;
  units: string | null;
  detectionLimit: number | null;
  referenceMethod: string;
  limitOperator: LimitOperator;
  limitMin: number | null;
  limitMax: number | null;
  limitDisplay: string;
  qualitativeAllowed: string[];
  isAccredited: boolean;
  limitSource: string;
};

export const PRIORITY_PARAMETER_CODES = [
  'COLOR',
  'ODOUR',
  'TASTE',
  'EC',
  'PH',
  'TURBIDITY',
  'TDS',
  'TOTAL_COLIFORMS',
  'FECAL_COLIFORMS',
  'E_COLI',
] as const;

export function categoryToConformityGroup(
  category: ParameterCategory,
): ParameterConformityGroup {
  switch (category) {
    case 'PHYSICAL_AESTHETIC':
      return 'PHYSICAL';
    case 'CHEMICAL':
      return 'CHEMICAL';
    case 'TRACE_ELEMENT':
      return 'TRACE';
    case 'MICROBIOLOGICAL':
      return 'MICROBIAL';
    default: {
      const exhaustive: never = category;
      return exhaustive;
    }
  }
}

export function isPriorityParameter(code: string): boolean {
  return (PRIORITY_PARAMETER_CODES as readonly string[]).includes(code);
}

export const WATER_QUALITY_PARAMETERS: WaterQualityParameterDef[] = [
  {
    code: 'COLOR',
    name: 'Color',
    category: 'PHYSICAL_AESTHETIC',
    conformityGroup: 'PHYSICAL',
    sortOrder: 1,
    units: null,
    detectionLimit: null,
    referenceMethod: 'Sensory Evaluation',
    limitOperator: 'QUALITATIVE',
    limitMin: null,
    limitMax: null,
    limitDisplay: 'Colorless',
    qualitativeAllowed: ['Colorless', 'colourless'],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'ODOUR',
    name: 'Odour',
    category: 'PHYSICAL_AESTHETIC',
    conformityGroup: 'PHYSICAL',
    sortOrder: 2,
    units: null,
    detectionLimit: null,
    referenceMethod: 'Sensory Evaluation',
    limitOperator: 'QUALITATIVE',
    limitMin: null,
    limitMax: null,
    limitDisplay: 'Unobj',
    qualitativeAllowed: ['Unobj', 'Unobjectionable', 'Un-objectionable'],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'TASTE',
    name: 'Taste',
    category: 'PHYSICAL_AESTHETIC',
    conformityGroup: 'PHYSICAL',
    sortOrder: 3,
    units: null,
    detectionLimit: null,
    referenceMethod: 'Sensory Evaluation',
    limitOperator: 'QUALITATIVE',
    limitMin: null,
    limitMax: null,
    limitDisplay: 'Unobj',
    qualitativeAllowed: ['Unobj', 'Unobjectionable', 'Un-objectionable'],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'EC',
    name: 'Electrical Conductivity',
    category: 'PHYSICAL_AESTHETIC',
    conformityGroup: 'PHYSICAL',
    sortOrder: 4,
    units: 'µS/cm',
    detectionLimit: 0.11,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'NONE',
    limitMin: null,
    limitMax: null,
    limitDisplay: 'NGVS',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'PH',
    name: 'pH',
    category: 'PHYSICAL_AESTHETIC',
    conformityGroup: 'PHYSICAL',
    sortOrder: 5,
    units: null,
    detectionLimit: 0.03,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'RANGE',
    limitMin: 6.5,
    limitMax: 8.5,
    limitDisplay: '6.5 - 8.5',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'TURBIDITY',
    name: 'Turbidity',
    category: 'PHYSICAL_AESTHETIC',
    conformityGroup: 'PHYSICAL',
    sortOrder: 6,
    units: 'NTU',
    detectionLimit: 0.31,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_EXCLUSIVE',
    limitMin: null,
    limitMax: 5,
    limitDisplay: '< 5',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'ALKALINITY',
    name: 'Alkalinity as CaCO3',
    category: 'CHEMICAL',
    conformityGroup: 'CHEMICAL',
    sortOrder: 7,
    units: 'mg/L',
    detectionLimit: 5,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'NONE',
    limitMin: null,
    limitMax: null,
    limitDisplay: 'NGVS',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'BICARBONATES',
    name: 'Bicarbonates',
    category: 'CHEMICAL',
    conformityGroup: 'CHEMICAL',
    sortOrder: 8,
    units: 'mg/L',
    detectionLimit: 5.0,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'NONE',
    limitMin: null,
    limitMax: null,
    limitDisplay: 'NGVS',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'CALCIUM',
    name: 'Calcium',
    category: 'CHEMICAL',
    conformityGroup: 'CHEMICAL',
    sortOrder: 9,
    units: 'mg/L',
    detectionLimit: 2.0,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'NONE',
    limitMin: null,
    limitMax: null,
    limitDisplay: 'NGVS',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'CARBONATES',
    name: 'Carbonates',
    category: 'CHEMICAL',
    conformityGroup: 'CHEMICAL',
    sortOrder: 10,
    units: 'mg/L',
    detectionLimit: 5.0,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'NONE',
    limitMin: null,
    limitMax: null,
    limitDisplay: 'NGVS',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'CHLORIDES',
    name: 'Chlorides',
    category: 'CHEMICAL',
    conformityGroup: 'CHEMICAL',
    sortOrder: 11,
    units: 'mg/L',
    detectionLimit: 2.0,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_EXCLUSIVE',
    limitMin: null,
    limitMax: 250,
    limitDisplay: '< 250',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'TOTAL_HARDNESS',
    name: 'Total Hardness',
    category: 'CHEMICAL',
    conformityGroup: 'CHEMICAL',
    sortOrder: 12,
    units: 'mg/L',
    detectionLimit: 5.0,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_EXCLUSIVE',
    limitMin: null,
    limitMax: 500,
    limitDisplay: '< 500',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'MAGNESIUM',
    name: 'Magnesium',
    category: 'CHEMICAL',
    conformityGroup: 'CHEMICAL',
    sortOrder: 13,
    units: 'mg/L',
    detectionLimit: 1.0,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'NONE',
    limitMin: null,
    limitMax: null,
    limitDisplay: 'NGVS',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'POTASSIUM',
    name: 'Potassium',
    category: 'CHEMICAL',
    conformityGroup: 'CHEMICAL',
    sortOrder: 14,
    units: 'mg/L',
    detectionLimit: 0.02,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'NONE',
    limitMin: null,
    limitMax: null,
    limitDisplay: 'NGVS',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'SODIUM',
    name: 'Sodium',
    category: 'CHEMICAL',
    conformityGroup: 'CHEMICAL',
    sortOrder: 15,
    units: 'mg/L',
    detectionLimit: 1.57,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'NONE',
    limitMin: null,
    limitMax: null,
    limitDisplay: 'NGVS',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'SULPHATE',
    name: 'Sulphate',
    category: 'CHEMICAL',
    conformityGroup: 'CHEMICAL',
    sortOrder: 16,
    units: 'mg/L',
    detectionLimit: 0.28,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'NONE',
    limitMin: null,
    limitMax: null,
    limitDisplay: 'NGVS',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'NITRATE_N',
    name: 'Nitrate (N)',
    category: 'CHEMICAL',
    conformityGroup: 'CHEMICAL',
    sortOrder: 17,
    units: 'mg/L',
    detectionLimit: 0.06,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_EXCLUSIVE',
    limitMin: null,
    limitMax: 10,
    limitDisplay: '< 10',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'NITRITE',
    name: 'Nitrite',
    category: 'CHEMICAL',
    conformityGroup: 'CHEMICAL',
    sortOrder: 18,
    units: 'mg/L',
    detectionLimit: 0.05,
    referenceMethod: 'USEPA, 2000',
    limitOperator: 'MAX_EXCLUSIVE',
    limitMin: null,
    limitMax: 3,
    limitDisplay: '< 3',
    qualitativeAllowed: [],
    isAccredited: false,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'TDS',
    name: 'TDS',
    category: 'CHEMICAL',
    conformityGroup: 'CHEMICAL',
    sortOrder: 19,
    units: 'mg/L',
    detectionLimit: null,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_EXCLUSIVE',
    limitMin: null,
    limitMax: 1000,
    limitDisplay: '< 1000',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'IRON',
    name: 'Iron',
    category: 'CHEMICAL',
    conformityGroup: 'CHEMICAL',
    sortOrder: 20,
    units: 'mg/L',
    detectionLimit: 0.04,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_INCLUSIVE',
    limitMin: null,
    limitMax: 0.3,
    limitDisplay: '0.3 (WHO, 2004)',
    qualitativeAllowed: [],
    isAccredited: false,
    limitSource: 'WHO, 2004',
  },
  {
    code: 'FLUORIDE',
    name: 'Fluoride',
    category: 'CHEMICAL',
    conformityGroup: 'CHEMICAL',
    sortOrder: 21,
    units: 'mg/L',
    detectionLimit: 0.06,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_INCLUSIVE',
    limitMin: null,
    limitMax: 1.5,
    limitDisplay: '1.5',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'PHOSPHATE',
    name: 'Phosphate',
    category: 'CHEMICAL',
    conformityGroup: 'CHEMICAL',
    sortOrder: 22,
    units: 'mg/L',
    detectionLimit: 0.05,
    referenceMethod: 'USEPA, 2000',
    limitOperator: 'NONE',
    limitMin: null,
    limitMax: null,
    limitDisplay: 'NGVS',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'ALUMINUM',
    name: 'Aluminum',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 23,
    units: 'µg/L',
    detectionLimit: 0.15,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_INCLUSIVE',
    limitMin: null,
    limitMax: 200,
    limitDisplay: '200',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'ARSENIC',
    name: 'Arsenic',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 24,
    units: 'µg/L',
    detectionLimit: 0.13,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_INCLUSIVE',
    limitMin: null,
    limitMax: 50,
    limitDisplay: '50',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'BARIUM',
    name: 'Barium',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 25,
    units: 'µg/L',
    detectionLimit: 0.09,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_INCLUSIVE',
    limitMin: null,
    limitMax: 700,
    limitDisplay: '700',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'CADMIUM',
    name: 'Cadmium',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 26,
    units: 'µg/L',
    detectionLimit: 0.08,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_INCLUSIVE',
    limitMin: null,
    limitMax: 10,
    limitDisplay: '10',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'CHROMIUM',
    name: 'Chromium',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 27,
    units: 'µg/L',
    detectionLimit: 0.05,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_INCLUSIVE',
    limitMin: null,
    limitMax: 50,
    limitDisplay: '50',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'COPPER',
    name: 'Copper',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 28,
    units: 'µg/L',
    detectionLimit: 0.11,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_INCLUSIVE',
    limitMin: null,
    limitMax: 2000,
    limitDisplay: '2000',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'MANGANESE',
    name: 'Manganese',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 29,
    units: 'µg/L',
    detectionLimit: 0.06,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_INCLUSIVE',
    limitMin: null,
    limitMax: 500,
    limitDisplay: '500',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'MOLYBDENUM',
    name: 'Molybdenum',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 30,
    units: 'µg/L',
    detectionLimit: 0.15,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'NONE',
    limitMin: null,
    limitMax: null,
    limitDisplay: 'NGVS',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'NICKEL',
    name: 'Nickel',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 31,
    units: 'µg/L',
    detectionLimit: 0.15,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_INCLUSIVE',
    limitMin: null,
    limitMax: 20,
    limitDisplay: '20',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'LEAD',
    name: 'Lead',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 32,
    units: 'µg/L',
    detectionLimit: 0.16,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_INCLUSIVE',
    limitMin: null,
    limitMax: 50,
    limitDisplay: '50',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'SELENIUM',
    name: 'Selenium',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 33,
    units: 'µg/L',
    detectionLimit: 0.12,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_INCLUSIVE',
    limitMin: null,
    limitMax: 10,
    limitDisplay: '10',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'STRONTIUM',
    name: 'Strontium',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 34,
    units: 'µg/L',
    detectionLimit: 0.13,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'NONE',
    limitMin: null,
    limitMax: null,
    limitDisplay: 'NGVS',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'ZINC',
    name: 'Zinc',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 35,
    units: 'µg/L',
    detectionLimit: 0.08,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'MAX_INCLUSIVE',
    limitMin: null,
    limitMax: 5000,
    limitDisplay: '5000',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'BORON',
    name: 'Boron',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 36,
    units: 'mg/L',
    detectionLimit: null,
    referenceMethod: 'APHA 4500',
    limitOperator: 'MAX_INCLUSIVE',
    limitMin: null,
    limitMax: 0.3,
    limitDisplay: '0.3',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'ANTIMONY',
    name: 'Antimony',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 37,
    units: 'mg/L',
    detectionLimit: null,
    referenceMethod: 'APHA 3500',
    limitOperator: 'MAX_EXCLUSIVE',
    limitMin: null,
    limitMax: 0.005,
    limitDisplay: '<0.005',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'MERCURY',
    name: 'Mercury',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 38,
    units: 'mg/L',
    detectionLimit: null,
    referenceMethod: 'APHA 3500',
    limitOperator: 'MAX_EXCLUSIVE',
    limitMin: null,
    limitMax: 0.001,
    limitDisplay: '<0.001',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'CYANIDE',
    name: 'Cyanide',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 39,
    units: 'mg/L',
    detectionLimit: null,
    referenceMethod: 'APHA 4500',
    limitOperator: 'MAX_EXCLUSIVE',
    limitMin: null,
    limitMax: 0.05,
    limitDisplay: '<0.05',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'SILICA',
    name: 'Silica',
    category: 'TRACE_ELEMENT',
    conformityGroup: 'TRACE',
    sortOrder: 40,
    units: 'mg/L',
    detectionLimit: null,
    referenceMethod: 'APHA 4500',
    limitOperator: 'NONE',
    limitMin: null,
    limitMax: null,
    limitDisplay: 'NGVS',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'PSQCA / NSDWQ, 2010',
  },
  {
    code: 'TOTAL_COLIFORMS',
    name: 'Total Coliforms',
    category: 'MICROBIOLOGICAL',
    conformityGroup: 'MICROBIAL',
    sortOrder: 41,
    units: 'CFU/100 ml',
    detectionLimit: 0,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'EQUALS_ZERO',
    limitMin: null,
    limitMax: 0,
    limitDisplay: '0 (NSDWQ,2010)',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'NSDWQ, 2010',
  },
  {
    code: 'FECAL_COLIFORMS',
    name: 'Fecal Coliforms',
    category: 'MICROBIOLOGICAL',
    conformityGroup: 'MICROBIAL',
    sortOrder: 42,
    units: 'CFU/100 ml',
    detectionLimit: 0,
    referenceMethod: 'APHA, 23rd Edition',
    limitOperator: 'EQUALS_ZERO',
    limitMin: null,
    limitMax: 0,
    limitDisplay: '0 (NSDWQ,2010)',
    qualitativeAllowed: [],
    isAccredited: true,
    limitSource: 'NSDWQ, 2010',
  },
  {
    code: 'E_COLI',
    name: 'E-coli',
    category: 'MICROBIOLOGICAL',
    conformityGroup: 'MICROBIAL',
    sortOrder: 43,
    units: 'CFU/100 ml',
    detectionLimit: 0,
    referenceMethod: 'USEPA-1603',
    limitOperator: 'EQUALS_ZERO',
    limitMin: null,
    limitMax: 0,
    limitDisplay: '0 (NSDWQ,2010)',
    qualitativeAllowed: ['-ve', 'negative', 'absent', 'nd', 'nil'],
    isAccredited: true,
    limitSource: 'NSDWQ, 2010',
  },
];
