import {
  BadRequestException,
  ConflictException,
  Inject,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import {
  AuditAction,
  AUDIT_LOG_REPOSITORY,
  type AuditLogRepository,
} from '../../domain/audit/audit-log';
import {
  USER_REPOSITORY,
  type ListUsersFilter,
  type UserRepository,
} from '../../domain/user/repositories/user.repository';
import {
  organizationForRole,
  toPublicUser,
  UserRole,
  type PublicUser,
} from '../../domain/user/user';
import { PasswordService } from '../../infrastructure/security/password.service';

export type CreateUserCommand = {
  name: string;
  email: string;
  password?: string;
  autoGeneratePassword?: boolean;
  role: UserRole;
  organization?: string | null;
  actorId: string;
  ipAddress?: string;
};

export type UpdateUserCommand = {
  userId: string;
  name?: string;
  organization?: string | null;
  role?: UserRole;
  actorId: string;
  ipAddress?: string;
};

@Injectable()
export class AdminUsersUseCase {
  constructor(
    @Inject(USER_REPOSITORY)
    private readonly users: UserRepository,
    @Inject(AUDIT_LOG_REPOSITORY)
    private readonly auditLogs: AuditLogRepository,
    private readonly passwords: PasswordService,
  ) {}

  async list(filter?: ListUsersFilter): Promise<PublicUser[]> {
    const users = await this.users.list(filter);
    return users.map((user) => toPublicUser(user));
  }

  async getById(id: string): Promise<PublicUser> {
    const user = await this.users.findById(id);
    if (!user) {
      throw new NotFoundException('User not found');
    }
    return toPublicUser(user);
  }

  async create(command: CreateUserCommand): Promise<{
    user: PublicUser;
    initialPassword: string;
  }> {
    const existing = await this.users.findByEmail(command.email);
    if (existing) {
      throw new ConflictException('Email is already registered');
    }

    const wasAutoGenerated = command.autoGeneratePassword === true;
    const plainPassword = wasAutoGenerated
      ? this.passwords.generateTemporaryPassword()
      : command.password?.trim() || PasswordService.DEFAULT_INITIAL_PASSWORD;
    const passwordHash = await this.passwords.hash(plainPassword);
    const organization = organizationForRole(command.role);

    const user = await this.users.create({
      name: command.name.trim(),
      email: command.email.trim().toLowerCase(),
      passwordHash,
      role: command.role,
      organization,
      mustChangePassword: wasAutoGenerated,
    });

    await this.auditLogs.create({
      action: AuditAction.USER_CREATED,
      actorId: command.actorId,
      targetId: user.id,
      metadata: {
        role: user.role,
        email: user.email,
        organization: user.organization,
        passwordAutoGenerated: wasAutoGenerated,
      },
      ipAddress: command.ipAddress,
    });

    return {
      user: toPublicUser(user),
      initialPassword: plainPassword,
    };
  }

  async update(command: UpdateUserCommand): Promise<PublicUser> {
    const existing = await this.users.findById(command.userId);
    if (!existing) {
      throw new NotFoundException('User not found');
    }

    if (
      existing.role === UserRole.SYSTEM_ADMIN &&
      command.role &&
      command.role !== UserRole.SYSTEM_ADMIN
    ) {
      const adminCount = await this.users.countByRole(UserRole.SYSTEM_ADMIN);
      if (adminCount <= 1) {
        throw new BadRequestException(
          'Cannot demote the last SYSTEM_ADMIN account',
        );
      }
    }

    const nextRole = command.role ?? existing.role;
    const organization =
      command.organization !== undefined || command.role !== undefined
        ? organizationForRole(nextRole)
        : undefined;

    const updated = await this.users.update(command.userId, {
      name: command.name,
      organization,
      role: command.role,
    });

    if (command.role && command.role !== existing.role) {
      await this.auditLogs.create({
        action: AuditAction.ROLE_CHANGED,
        actorId: command.actorId,
        targetId: updated.id,
        metadata: {
          from: existing.role,
          to: command.role,
          organization: updated.organization,
        },
        ipAddress: command.ipAddress,
      });
    } else {
      await this.auditLogs.create({
        action: AuditAction.USER_UPDATED,
        actorId: command.actorId,
        targetId: updated.id,
        metadata: {
          name: command.name,
          organization: updated.organization,
        },
        ipAddress: command.ipAddress,
      });
    }

    return toPublicUser(updated);
  }

  async setActive(
    userId: string,
    isActive: boolean,
    actorId: string,
    ipAddress?: string,
  ): Promise<PublicUser> {
    const existing = await this.users.findById(userId);
    if (!existing) {
      throw new NotFoundException('User not found');
    }

    if (!isActive && existing.role === UserRole.SYSTEM_ADMIN) {
      const adminCount = await this.users.countByRole(UserRole.SYSTEM_ADMIN);
      if (adminCount <= 1) {
        throw new BadRequestException(
          'Cannot deactivate the last SYSTEM_ADMIN account',
        );
      }
    }

    if (userId === actorId && !isActive) {
      throw new BadRequestException('Cannot deactivate your own account');
    }

    const updated = await this.users.update(userId, { isActive });
    await this.auditLogs.create({
      action: isActive
        ? AuditAction.USER_ACTIVATED
        : AuditAction.USER_DEACTIVATED,
      actorId,
      targetId: userId,
      ipAddress,
    });

    return toPublicUser(updated);
  }

  async resetPassword(
    userId: string,
    actorId: string,
    newPassword?: string,
    ipAddress?: string,
  ): Promise<{ user: PublicUser; temporaryPassword: string }> {
    const existing = await this.users.findById(userId);
    if (!existing) {
      throw new NotFoundException('User not found');
    }

    const temporaryPassword =
      newPassword?.trim() || this.passwords.generateTemporaryPassword();
    const passwordHash = await this.passwords.hash(temporaryPassword);

    const updated = await this.users.update(userId, {
      passwordHash,
      mustChangePassword: true,
    });

    await this.auditLogs.create({
      action: AuditAction.PASSWORD_RESET,
      actorId,
      targetId: userId,
      ipAddress,
    });

    return {
      user: toPublicUser(updated),
      temporaryPassword,
    };
  }
}
